all:
	g++ Principal.cpp Cuadro.cpp --std=c++17 -I/home/computacion/opencv/opencvi/include/opencv4/ -L/home/computacion/opencv/opencvi/lib/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -lopencv_photo -o vision.bin
	
run:
	./vision.bin

saludo:
	echo "Hola mundo C++"